app:
  name: mini-jupiter
  env: baseline
http:
  addr: ":8080"
log:
  level: "info"
  encoding: "console"
middleware:
  recovery: false
  trace_id: false
  logging: false
metric:
  enabled: false
  path: "/metrics"
  namespace: "mini_jupiter"
ratelimit:
  enabled: false
  rate: 5
  burst: 10
